apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: vanshikacon.azurecr.io/tomcatdocker:6
        name: my-app
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
